# Example config file for development

PROJECT_URL: 'http://localhost:5006'

DEBUG: true

ADMINS:
  - 'dev@binary-butterfly.de'
MAILS_FROM: 'dev@binary-butterfly.de'

SECRET_KEY: 'random-key'
SQLALCHEMY_DATABASE_URI: 'postgresql://park-api:development@postgresql/park-api'
# Alternative: MariaDB / MySQL:
# SQLALCHEMY_DATABASE_URI: 'mysql+pymysql://root:root@mysql/park-api'

CELERY_BROKER_URL: 'amqp://rabbitmq'

PARK_API_CONVERTER:
  - some-source
  - another-source

SERVER_AUTH_USERS:
  dev:
    hash: 9f86d081884c7d659a2feaa0c55ad015a3bf4f1b2b0b822cd15d6c15b0f00a08
    roles:
      - user

# Stdout Logging (useful especially for development)
STDOUT_LOGGING_ENABLED: true

# Loki Logging Client
LOKI_ENABLED: false
LOKI_URL: https://your-monitoring-host/loki/api/v1/push
LOKI_USER: loki
LOKI_PASSWORD: password
LOKI_TAGS:
  service: park-api
